apiVersion: apps/v1
kind: Deployment
metadata:
  name: about-me-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: about-me
  revisionHistoryLimit: 5
  progressDeadlineSeconds: 300
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: about-me
    spec:
      containers:
      - name: about-me-pod
        image: starfall0/docker-k8s:v1
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: 128Mi
            cpu: 0.1