apiVersion: v1
kind: Service
metadata:
  name: me-svc
  labels:
    app: nginx-git-sync
spec:
  type: NodePort
  ports:
  - port: 80
    nodePort: 30001
    protocol: TCP
  selector:
    app: nginx-git-sync